# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: napi-dotnet build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Enable manually starting a build

permissions:
  checks: write
  pull-requests: write
  statuses: write

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        dotnet-version: [ 7.0.x ]
        node-version: [ 18.x ]
      fail-fast: false  # Don't cancel other jobs when one job fails

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: dotnet build --configuration Release

    - name: pack
      run: dotnet pack --no-build --configuration Release

    # Uncomment to enable an SSH session for debugging
    # - name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  with:
    #      limit-access-to-actor: true

    - name: Test
      env:
        NODE_API_DOTNET_TRACE: 1
      run: dotnet test --no-build --configuration Release --logger trx --results-directory "test-${{ matrix.dotnet-version }}-node${{ matrix.node-version }}"

    - name: Upload test logs
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-${{ runner.os }}-dotnet${{ matrix.dotnet-version }}-node${{ matrix.node-version }}
        path: out/obj/Release/**/*.log
      if: ${{ always() }}

    - name: Publish test results
      uses: dorny/test-reporter@v1
      with:
        name: test (${{ runner.os }}, dotnet${{ matrix.dotnet-version }}, node${{ matrix.node-version }})
        path: test-${{ matrix.dotnet-version }}-node${{ matrix.node-version }}/*.trx
        reporter: dotnet-trx
      if: ${{ always() }} # Run this step even when there are test failures

    - name: Check formatting
      run: |
        dotnet tool install -g dotnet-format --version "7.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
        dotnet format --no-restore --severity info --verbosity detailed --verify-no-changes
      if: ${{ always() }} # Run this step even when there are build failures

    # TODO: Publish packages
    # - name: Publish packages
    #   run: dotnet nuget push out/pkg/*.nupkg
